### ISSUE TITLE
Feature request: Regex / Custom searches

### ISSUE THREAD

**Issue by securityserviceaccount** [ankane/pdscan#1]
It would be awesome to easily modify your app to search for custom regex strings.

**Comment by ankane** [comment]
Hey @securityserviceaccount, thanks for the suggestion. What use case(s) are you thinking about for this?

If you're familiar with Go, you can also add your own here: 
https://github.com/ankane/pdscan/blob/99af7a3794f35528f106759bba238ad0ed9f8d5f/internal/helpers.go#L88

**Comment by ankane** [comment]
Closing due to no response
