### ISSUE TITLE
go-redis context timeout is too short

### ISSUE THREAD

**Issue by skyleronken** [ankane/pdscan#15]
`internal/redis_adapter.go` is using a 5 second timeout in two locations which is too short. It needs to be increased to something like 50 seconds.

**Comment by ankane** [comment]
Hi @skyleronken, can you share the error and stack trace you’re seeing, along with more context about the situation? I think 5 seconds should be plenty of time for most operations.

**Comment by skyleronken** [comment]
There is no stack trace since the error is handled gracefully. Here is the output:

```
pdscan` redis://REDACTED:6379 --sample-size 10 --show-data --processes 10                                                                                                                           
Found 1 database to scan, sampling 10 keys from each...

Error: context deadline exceeded
```

The above error does not occur if I reduce the sample-size, but at a cost of false negatives. 

It looks like the initial context defined in the RedisAdapter Init() method seems to be fine. However, the context timeout defined in RedisAdapter.FetchTableData() is too short since the processing time appears to be a function of latency, sample-size, and processes.

**Comment by ankane** [comment]
Great, thanks @skyleronken! Can you add debugging to see which calls are timing out? I think we’ll probably want to limit the items fetched from lists, sorted sets, etc rather than increase the timeout (since those calls are likely placing a high load on Redis)

**Comment by ankane** [comment]
Switched to scan commands in the commit above, which should eliminate the timeouts.
