### ISSUE TITLE
Development instructions

### ISSUE THREAD

**Issue by llermaly** [ankane/pdscan#17]
Hello, I would like to extend pdscan and test things but I can't figure out how to do it.

I followed the documentation, forked, cloned and then ran `make test` but it just run a list of tests. 

What's the process to for example add a new regex pattern and then run ./pdscan ? 

I tried doing make install but no pdscan folder is created. I hope you can give me a hand.

**Comment by llermaly** [comment]
I did `go build` and then the pdscan file appeared. 

Is this the way to go? or is there something like a live/watcher mode? thanks!

**Comment by ankane** [comment]
Hi @llermaly, the easiest way is probably `go run . [args]`.

There's also an experimental `--pattern` option you can use to specify a custom pattern without any code changes.

**Comment by llermaly** [comment]
Thank you very much!
