### ISSUE TITLE
Redshift Support?

### ISSUE THREAD

**Issue by khanson615** [ankane/pdscan#2]
Hello,

Thank you for creating this tool, it's great! Do you happen to know if there's anything preventing me from using the postgres functionality against a AWS Redshift database? I tried it last night, and got a permissions error. But I'm not sure why. Do you know of any issues with Redshift specifically?

**Comment by ankane** [comment]
Hey @khanson615, I haven't tried it with Redshift, but it shouldn't be too hard to support if it doesn't work already. Can you paste the error message?

**Comment by khanson615** [comment]
The error is 'password authentication failed for user "db_user".' So it seems like authentication error, however we've confirmed that the password is valid. So that's what led is to believe it was something Redshift-specific.

**Comment by ankane** [comment]
Hey @khanson615, just pushed an update for that error. You can get the latest version with:

```sh
go get github.com/ankane/pdscan
```

You can pass a large value to `--sample-size` if you want to check all rows (not recommended). There's not a way to exclude tables right now.

**Comment by khanson615** [comment]
Awesome! Thank you very much Andrew!

**Comment by khanson615** [comment]
Will that update make it into the Linux-specific package?

**Comment by ankane** [comment]
Not until the next release (don't have a timeline).

**Comment by khanson615** [comment]
Is there a way that I could compile it myself?

**Comment by ankane** [comment]
If you install Go and dep, you can follow the instructions in the Contributing section of the readme. To produce a binary, run:

```sh
go build
```

**Comment by ankane** [comment]
Did you have a chance to try it?

**Comment by khanson615** [comment]
Nope. I haven’t had a chance to compile the new code yet. Hopefully going to work on it tonight or tomorrow.

Kind regards,
Ken Hanson

**Comment by khanson615** [comment]
Hi Andrew,

I had a chance to pull down the latest (I think) code package, and it's still throwing the same error around the "pg_extension" relation. Is it something I'm doing wrong?

**Comment by khanson615** [comment]
Hi Andrew!

Sorry to be a bother, but any update on this?

Kind regards,
Ken

**Comment by ankane** [comment]
@khanson615 Not sure how I can help any further. Make sure you're using the binary built from source.

**Comment by ankane** [comment]
Cleaning up issues
