### ISSUE TITLE
Tool exits on attempt to read empty file

### ISSUE THREAD

**Issue by rjcortese** [ankane/pdscan#6]
Currently when you pass a directory to check, if there is an empty file, attempting `reader.Peek(261)` will fail and the program will call `os.Exit(1)`.
I have fixed this in a fork and now
`matchedValues, count := adapter.FindFileMatches(file)`
will return a count = 0 and then the code after that line will handle it correctly.
If that sounds agreeable to you, let me know and I will submit a pull request.

**Comment by ankane** [comment]
Hey @rjcortese, this would be great as well.
