### ISSUE TITLE
Empty buffer error when scanning directory path on Mac

### ISSUE THREAD

**Issue by jamiegs** [ankane/pdscan#9]
I'm trying to run pdscan on a Mac running Big Sur 11.3.1 and I get an Empty Buffer error.

What would cause this error?

> pdscan file:///Users/filepath/
```
Found 339678 files to scan...

Empty buffer
```

**Comment by zmead38** [comment]
Second here on Windows.

Found 36 files to scan...

Empty buffer

**Comment by ankane** [comment]
Hey all, thanks for reporting! Just pushed a fix and will try to get a new release out later today.
